# Generated by Django 4.0 on 2021-12-26 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_made',
            name='donation_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_request_donations_made', to='accounts.donation_request'),
        ),
        migrations.AlterField(
            model_name='donation_made',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_user_donations_made', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='donation_made',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user_donations_made', to='accounts.user'),
        ),
    ]
