# Generated by Django 3.1.4 on 2021-03-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='mode',
            field=models.CharField(choices=[('Donate', 'Donate'), ('Recieve', 'Recieve')], max_length=10, null=True),
        ),
    ]
