# Generated by Django 3.1.4 on 2021-04-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_donation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='mode',
            field=models.CharField(choices=[('Donate', 'Donate'), ('Receive', 'Receive')], max_length=10, null=True),
        ),
    ]
