# Generated by Django 3.1.4 on 2021-04-30 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210407_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='donation',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_from_user', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='donation',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_to_user', to='accounts.user'),
        ),
    ]
