# Generated by Django 3.1.4 on 2021-04-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210430_2304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customers',
        ),
    ]
