# Generated by Django 3.1.4 on 2021-04-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210501_0011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='User',
        ),
    ]
