# Generated by Django 3.1.4 on 2021-05-06 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_auto_20210501_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation_made',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('G-Pay', 'G-Pay'), ('PayPal', 'PayPal'), ('Paytm', 'Paytm')], max_length=100, null=True)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('goal', models.PositiveIntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('amount_received', models.PositiveIntegerField(default=0)),
                ('updates', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.AddField(
            model_name='donation_request',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='donation_made',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_from_user', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='donation_made',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_to_user', to='accounts.customer'),
        ),
    ]
