# Generated by Django 3.1.4 on 2021-05-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210506_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_request',
            name='updates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
