# Generated by Django 3.1.4 on 2021-05-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210506_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_request',
            name='short_description',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
