# Generated by Django 3.1.4 on 2021-06-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210515_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_request',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
