# Generated by Django 3.1.4 on 2021-06-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_donation_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_request',
            name='random_image_number',
            field=models.CharField(default='1596448', max_length=7),
        ),
    ]
