# Generated by Django 3.1.4 on 2021-06-05 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_donation_request_random_image_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_request',
            name='random_image_number',
            field=models.CharField(default='739202', max_length=7),
        ),
        migrations.AlterField(
            model_name='donation_request',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
