# Generated by Django 3.1.4 on 2021-06-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210605_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_request',
            name='random_image_number',
            field=models.CharField(default='590161', max_length=7),
        ),
    ]
