# Generated by Django 3.1.4 on 2021-06-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210605_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_request',
            name='image_extension',
            field=models.CharField(default='.jpg', max_length=4),
        ),
        migrations.AlterField(
            model_name='donation_request',
            name='random_image_number',
            field=models.CharField(default='2444748', max_length=7),
        ),
    ]
