# Generated by Django 3.1.4 on 2021-06-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210610_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation_request',
            name='image_extension',
        ),
        migrations.RemoveField(
            model_name='donation_request',
            name='random_image_number',
        ),
        migrations.AddField(
            model_name='donation_request',
            name='request_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='random_image_number',
            field=models.CharField(default='9947047', max_length=7),
        ),
        migrations.AlterField(
            model_name='donation_request',
            name='short_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
