# Generated by Django 3.1.4 on 2021-06-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20210614_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image_extension',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='random_image_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='donation_request',
            name='request_image',
            field=models.ImageField(null=True, upload_to='donations'),
        ),
    ]
