# Generated by Django 3.1.4 on 2021-06-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20210614_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation_made',
            name='method',
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
