# Generated by Django 3.1.4 on 2021-06-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210617_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_request',
            name='updates',
            field=models.TextField(blank=True, default=''),
        ),
    ]
