# Generated by Django 4.0 on 2021-12-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_donation_made_datetime_of_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile/default-image.jpg', null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='donation_request',
            name='request_image',
            field=models.ImageField(default='donations/default-image.jpg', null=True, upload_to='donations'),
        ),
    ]
